## p01_sim_nomatch.r
## dcmuller
##
## process and analyse simulation samples generated by p01_sim_nomatch.r 
library(ggplot2)
library(devtools)
library(data.table)
library(reshape2)
library(survival)

## Install dcmMisc version 0.1 from github if it is not available
version_dcmMisc <- 0.1
if ("dcmMisc" %in% rownames(installed.packages()) == FALSE) {
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
if (installed.packages()["dcmMisc", "Version"] != version_dcmMisc) {
  warning(paste("replacing dcmMisc with version", version_randsurv))
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
library(dcmMisc)


## read data and rename
samples <- read.csv("./analysis/output/o01_all_samples.csv",
                    stringsAsFactors = FALSE)
samples <- rename(samples, 
                  c("X", "param"), 
                  c("sim_id", "param_type"))

## create an indentifier for which se goes with which coef
samples$sim_id <- floor((samples$sim_id + 1)/2)

## data.tables are faster and easier to manipulate
samples <- data.table(samples, key = c("settings", "model", "param_type"))

## 'melted', or long copy of the results to facilitate calculations and plotting
samples_long <- melt(samples, 
                     id.vars       = c("settings", "model", "param_type", "sim_id"), 
                     measure.vars  = c("intercept", "exposure", "log_scale"), 
                     value.name    = "estimate",
                     variable.name = "param")
samples_long <- data.table(samples_long)
samples_long$param<- as.character(samples_long$param)
setkey(samples_long, settings, model, param_type, param)


## summary table by model
summary_samples <- samples_long[,  
                                list(mean  = mean(estimate),
                                     sd    = sd(estimate),
                                     min   = min(estimate),
                                     max   = max(estimate))
                                , by = c("settings", 
                                         "model", 
                                         "param", 
                                         "param_type")]
setkey(summary_samples, model, param, param_type)
summary_samples

## build prediction dataset for plotting survival curves
samples_weighted <- samples[model == "weighted" & param_type == "coef", ]
samples_weighted$sim <- c(1:nrow(samples_weighted))

## linear predictor
##  (use matrix "x" to specify exposure values for the exposure variable)
x <- matrix(c(1,-1, 1, 0, 1, 1), nrow=2)
xb <- as.matrix(samples_weighted[, list(intercept, exposure)]) %*% x
samples_weighted <- data.frame(samples_weighted, xb)
samples_weighted <- melt(samples_weighted, 
                         id.vars = c("settings", "model", "param_type", 
                                     "sim_id", "sim", "intercept", 
                                     "exposure", "log_scale"),
                         value.name = "xb",
                         variable.name = "x")

## times at which to evaluate the survivor function
t <- seq(30, 80, by = 0.5)
time_mat <- matrix(rep(t, each=nrow(samples_weighted)), nrow=nrow(samples_weighted))
pred <- cbind(samples_weighted, time_mat)
pred_long <- melt(pred, 
                  id.vars    = c("settings", "model", "param_type", "sim_id", 
                                 "sim", "intercept", "exposure", "log_scale",
                                 "x", "xb"), 
                  value.name = "time")
pred_long <- data.table(pred_long)

## S(t) = exp(-lambda * t^p)
pred_long$p <- 1/exp(pred_long$log_scale)
pred_long$lambda <- exp(-pred_long$p * pred_long$xb)
pred_long$surv <- exp(-pred_long$lambda * (pred_long$time-30)^pred_long$p)
pred_long$pr <- 1 - pred_long$surv

## plot survival function from each simulation
pred_long$plotgroup <- paste0(pred_long$x, pred_long$sim)
surv_plot <- ggplot(data=pred_long[settings==1], 
                    aes(x = time, 
                        y = pr, 
                        group = plotgroup, 
                        colour = x))
surv_plot <- surv_plot +  theme_bw()
surv_plot <- surv_plot + geom_line(alpha = I(1/sqrt(max(pred_long$sim)*4)))
surv_plot

## "True" survival function
params <- read.csv("./analysis/output/o01_params.csv")
hr <- exp(params[1, "lhr"])
origin <- params[1, "origin"]
weib_param <- params[1, "weib_param1"]
lambda0 <-c(1/hr, 1, hr) * params[1, "baseline_rate1"] 
lambda0 <- rep(lambda0, each = length(t))
surv_true <- exp(-lambda0*(t-origin)^weib_param)
true <- data.frame(time = t, 
                   surv = surv_true, 
                   lambda = lambda0,
                   pr   = 1-surv_true,
                   plotgroup = rep(0, length(surv_true)),
                   x = rep(c("X1", "X2", "X3"), each=length(t)))
                   
surv_plot <- surv_plot + geom_line(data = true, 
                                   aes(x = time, 
                                       y = pr, 
                                       group = x))
surv_plot
