## p01_sim_nomatch.r
## dcmuller
##
## process and analyse simulation samples generated by p01_sim_nomatch.r 
library(ggplot2)
library(devtools)
library(data.table)
library(reshape2)
library(survival)
library(Hmisc)
library(Cairo)

## Install dcmMisc version 0.1 from github if it is not available
version_dcmMisc <- 0.1
if ("dcmMisc" %in% rownames(installed.packages()) == FALSE) {
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
if (installed.packages()["dcmMisc", "Version"] != version_dcmMisc) {
  warning(paste("replacing dcmMisc with version", version_randsurv))
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
library(dcmMisc)

## read parameter settings for simulations
params <- read.csv("./analysis/output/o01_params.csv", stringsAsFactors = FALSE)
params <- data.table(params)

## read data and rename
samples <- read.csv("./analysis/output/o01_all_samples.csv",
                    stringsAsFactors = FALSE)
samples <- rename(samples, 
                  c("X", "param"), 
                  c("sim_id", "param_type"))

## create an indentifier for which se goes with which coef
samples$sim_id <- floor((samples$sim_id + 1)/2)

## data.tables are faster and easier to manipulate
samples <- data.table(samples, key = c("settings", "model", "param_type"))

## 'melted', or long copy of the results to facilitate calculations and plotting
samples_long <- melt(samples, 
                     id.vars       = c("settings", "model", "param_type", "sim_id"), 
                     measure.vars  = c("intercept", "exposure", "log_scale"), 
                     value.name    = "estimate",
                     variable.name = "param")
samples_long <- data.table(samples_long)
samples_long$param<- as.character(samples_long$param)
setkey(samples_long, settings, model, param_type, param)

## put se's next to the relevant estimate
samples_long$tempid <- with(samples_long,
                            paste0(settings, "_", model, "_", 
                                   param, "_", sim_id))
samples_est_se <- as.data.frame(samples_long)
samples_est_se <- reshape(samples_est_se, 
                          v.names="estimate", 
                          idvar="tempid", 
                          sep="_", 
                          direction="wide", 
                          timevar="param_type")
samples_est_se$tempid <- NULL
samples_est_se <- data.table(samples_est_se)
setkey(samples_est_se, settings, model, param)

## merge with "true" log hazard ratio
true_lhr <- params[, list(settings, lhr)]
samples_est_se <- merge(true_lhr, samples_est_se, by="settings")

## coverage
samples_est_se[, lci:=estimate_coef - 1.96*estimate_se]
samples_est_se[, uci:=estimate_coef + 1.96*estimate_se]
samples_est_se[, truecovered:=ifelse(param=="exposure",
                                     as.numeric(lci <= lhr & lhr <= uci),
                                     NA)]

## summary table by model
summary_samples <- samples_est_se[,  
                                  list(mean_coef  = mean(estimate_coef),
                                       sd_coef    = sd(estimate_coef),
                                       mean_se    = mean(estimate_se),
                                       sd_se      = sd(estimate_se),
                                       coverage   = mean(truecovered))
                                  , by = c("settings", 
                                           "model", 
                                           "param")]
setkey(summary_samples, model, param)
summary_samples

## table for comparison of full cox and weighted cox
tabcox <- summary_samples[(model == "coxfull" | model == "coxweighted") 
                            & param == "exposure",
                          list(settings, model, 
                               mean_coef, sd_coef,
                               mean_se, sd_se,
                               coverage)]
tabcox_1 <- tabcox[settings == 1]
tabcox_1[, settings:=NULL]
tabcox_1 <- data.frame(tabcox_1)
tabcox_2 <- tabcox[settings == 2]
tabcox_2[, settings:=NULL]
tabcox_2 <- data.frame(tabcox_2)
tabcox <- rbind.data.frame(tabcox_2, tabcox_1)
rownames(tabcox) <- c("common disease", "", "rare disease", " ")
for (i in 1:ncol(tabcox)) {
  if (is.numeric(tabcox[, i])) {
    tabcox[, i] <- round(tabcox[, i], 3)
  }
}
tabcox[["model"]] <- ifelse(tabcox[["model"]] == "coxfull", 
                            "Full cohort", 
                            "Weighted NCC")
colnames(tabcox) <- c("analysis",
                      "mean(log HR)", "sd(log HR)", 
                      "mean(se(log HR))", "sd(se(log HR))",
                      "CI coverage")
textab <- latex(tabcox, 
                file = "./analysis/output/t02_cox_full_vs_ncc.tex", 
                booktabs = TRUE, 
                rowlabel = "")


## build prediction dataset for plotting survival curves
samples_weighted <- samples[model == "weighted" & param_type == "coef", ]
samples_weighted$sim <- c(1:nrow(samples_weighted))

## linear predictor
##  (use matrix "x" to specify exposure values for the exposure variable)
x <- matrix(c(1,-1, 1, 0, 1, 1), nrow=2)
xb <- as.matrix(samples_weighted[, list(intercept, exposure)]) %*% x
samples_weighted <- data.frame(samples_weighted, xb)
samples_weighted <- melt(samples_weighted, 
                         id.vars = c("settings", "model", "param_type", 
                                     "sim_id", "sim", "intercept", 
                                     "exposure", "log_scale"),
                         value.name = "xb",
                         variable.name = "x")

## times at which to evaluate the survivor function
t <- seq(30, 80, by = 0.5)
time_mat <- matrix(rep(t, each=nrow(samples_weighted)), nrow=nrow(samples_weighted))
pred <- cbind(samples_weighted, time_mat)
pred_long <- melt(pred, 
                  id.vars    = c("settings", "model", "param_type", "sim_id", 
                                 "sim", "intercept", "exposure", "log_scale",
                                 "x", "xb"), 
                  value.name = "time")
pred_long <- data.table(pred_long)

## S(t) = exp(-lambda * t^p)
pred_long$p <- 1/exp(pred_long$log_scale)
pred_long$lambda <- exp(-pred_long$p * pred_long$xb)
pred_long$surv <- exp(-pred_long$lambda * (pred_long$time-30)^pred_long$p)
pred_long$pr <- 1 - pred_long$surv

####################################################
## Rare disease
## plot survival function from each simulation
pred_long$plotgroup <- paste0(pred_long$x, pred_long$sim)
surv_plot <- ggplot(data=pred_long[settings==1], 
                    aes(x = time, 
                        y = pr, 
                        group = plotgroup, 
                        colour = x))
surv_plot <- surv_plot +  theme_bw()
surv_plot <- surv_plot + geom_line(alpha = I(1/sqrt(max(pred_long$sim)*8)))
surv_plot <- surv_plot + scale_x_continuous(name = "Age (years)")
surv_plot <- surv_plot + scale_y_continuous(name = "Cumulative probability")

## "True" survival function
hr <- exp(params[1, lhr])
origin <- params[1, origin]
weib_param <- params[1, weib_param1]
lambda0 <-c(1/hr, 1, hr) * params[1, baseline_rate1] 
lambda0 <- rep(lambda0, each = length(t))
surv_true <- exp(-lambda0*(t-origin)^weib_param)
true <- data.frame(time = t, 
                   surv = surv_true, 
                   lambda = lambda0,
                   pr   = 1-surv_true,
                   plotgroup = rep(0, length(surv_true)),
                   x = rep(c("X1", "X2", "X3"), each=length(t)))
                   
surv_plot <- surv_plot + geom_line(data = true, 
                                   aes(x = time, 
                                       y = pr, 
                                       group = x))

CairoPDF(file = "./analysis/output/g02_cumul_risk_rare.pdf",
         width = 6, 
         height = 5)
surv_plot
dev.off()

######################################
## Common disease
## plot survival function from each simulation
pred_long$plotgroup <- paste0(pred_long$x, pred_long$sim)
surv_plot <- ggplot(data=pred_long[settings==2], 
                    aes(x = time, 
                        y = pr, 
                        group = plotgroup, 
                        colour = x))
surv_plot <- surv_plot +  theme_bw()
surv_plot <- surv_plot + geom_line(alpha = I(1/sqrt(max(pred_long$sim)*8)))
surv_plot <- surv_plot + scale_x_continuous(name = "Age (years)")
surv_plot <- surv_plot + scale_y_continuous(name = "Cumulative probability")

## "True" survival function
hr <- exp(params[2, lhr])
origin <- params[2, origin]
weib_param <- params[2, weib_param1]
lambda0 <-c(1/hr, 1, hr) * params[2, baseline_rate1] 
lambda0 <- rep(lambda0, each = length(t))
surv_true <- exp(-lambda0*(t-origin)^weib_param)
true <- data.frame(time = t, 
                   surv = surv_true, 
                   lambda = lambda0,
                   pr   = 1-surv_true,
                   plotgroup = rep(0, length(surv_true)),
                   x = rep(c("X1", "X2", "X3"), each=length(t)))
                   
surv_plot <- surv_plot + geom_line(data = true, 
                                   aes(x = time, 
                                       y = pr, 
                                       group = x))

CairoPDF(file = "./analysis/output/g02_cumul_risk_common.pdf",
         width = 6, 
         height = 5)
surv_plot
dev.off()
