## p01_sim_nomatch.r
## dcmuller
##
## process and analyse simulation samples generated by p01_sim_nomatch.r 
library(ggplot2)
library(devtools)
library(data.table)
library(reshape2)
library(survival)

## Install dcmMisc version 0.1 from github if it is not available
version_dcmMisc <- 0.1
if ("dcmMisc" %in% rownames(installed.packages()) == FALSE) {
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
if (installed.packages()["dcmMisc", "Version"] != version_dcmMisc) {
  warning(paste("replacing dcmMisc with version", version_randsurv))
  install_github("dcmMisc", 
                 username="dcmuller", 
                 ref=paste0("v", version_dcmMisc))
}
library(dcmMisc)


## read data and rename
samples <- read.csv("./analysis/output/o01_all_samples.csv",
                    stringsAsFactors = FALSE)
samples <- rename(samples, 
                  c("X", "param"), 
                  c("sim_id", "param_type"))

## create an indentifier for which se goes with which coef
samples$sim_id <- floor((samples$sim_id + 1)/2)

## data.tables are faster and easier to manipulate
samples <- data.table(samples, key = c("model", "param_type"))

## 'melted', or long copy of the results to facilitate calculations and plotting
samples_long <- melt(samples, 
                     id.vars       = c("model", "param_type", "sim_id"), 
                     measure.vars  = c("intercept", "exposure", "log_scale"), 
                     value.name    = "estimate",
                     variable.name = "param")
samples_long <- data.table(samples_long)
samples_long$param<- as.character(samples_long$param)
setkey(samples_long, model, param_type, param)


## summary table by model
summary_samples <- samples_long[,  
                                list(mean  = mean(estimate),
                                     sd    = sd(estimate),
                                     min   = min(estimate),
                                     max   = max(estimate))
                                , by = c("model", "param", "param_type")]
setkey(summary_samples, model, param, param_type)
summary_samples

## build prediction dataset for plotting survival curves
samples_weighted <- samples[model == "weighted" & param_type == "coef", ]
samples_weighted$sim <- c(1:nrow(samples_weighted))

## times at which to evaluate the survivor function
t <- seq(30, 80, by = 0.5)
time_mat <- matrix(rep(t, each=nrow(samples_weighted)), nrow=nrow(samples_weighted))
pred <- cbind(samples_weighted, time_mat)
pred_long <- melt(pred, 
                  id.vars    = c("model", "param_type", "sim_id", "sim", 
                                 "intercept", "exposure", "log_scale"), 
                  value.name = "time")
pred_long <- data.table(pred_long)

## S(t) = exp(-lambda * t^p)
pred_long$p <- 1/exp(pred_long$log_scale)
pred_long$lambda <- exp(-pred_long$p * pred_long$intercept)
pred_long$surv <- exp(-pred_long$lambda * (pred_long$time-30)^pred_long$p)
pred_long$pr <- 1 - pred_long$surv

## plot survival function from each simulation
surv_plot <- ggplot(data=pred_long, aes(x=time, y=pr, group=sim))
surv_plot <- surv_plot +  theme_bw()
surv_plot <- surv_plot + geom_line(alpha = I(1/sqrt(max(pred_long$sim)*4)))
surv_plot

## "True" survival function
baseline_rate <- 10e-5
weib_param <- 1.8
surv_true <- exp(-baseline_rate*(t-30)^weib_param)
true <- data.frame(time = t, 
                   surv = surv_true, 
                   pr   = 1-surv_true,
                   sim  = rep(0, length(t)))
surv_plot <- surv_plot + geom_line(data = true, 
                                   aes(x = time, y = pr))
surv_plot